apiVersion: v1
kind: Service
metadata:
  name: __k8s.service.name__
  labels:
    run: __k8s.service.name__
spec:
  type: LoadBalancer
  ports:
  - port: __k8s.service.port__
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    run: __k8s.selector__
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: __k8s.deployment.name__
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: __k8s.selector__
    spec:
      containers:
      - name: functionappfrontend
        image: cadull.azurecr.io/functionapp
        ports:
        - containerPort: 80